server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.184.130:3306/yun6
    username: root
    password: root

eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
